#!/bin/bash

sudo cp ./passed-way.service /usr/lib/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable passed-way.service
sudo systemctl stop passed-way.service
sudo systemctl start passed-way.service
sudo systemctl status passed-way.service
echo "Service created"