export const EXCEPTION_CODES = {
  // default
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',

  // jewelry
  JEWELRY_NOT_FOUND: 'JEWELRY_NOT_FOUND'
}
