import { ERROR_CODE as EC } from '@bibtrip/errors'
import { ERROR_CODE as SEC } from '@bibtrip/server'

export const ERROR_CODE = {
   ...EC,
   ...SEC,
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
    CONFIRM_EMAIL_IN_PROGRESS: 'CONFIRM_EMAIL_IN_PROGRESS',
    INCORRECT_CONFIRM_CODE: 'INCORRECT_CONFIRM_CODE',
    USER_NICKNAME_ALREADY_EXISTS: 'USER_NICKNAME_ALREADY_EXISTS',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    INCORRECT_SHORT_LINK: 'INCORRECT_SHORT_LINK',
}

// inversify
export const INJECTION_TYPE = {
    CONFIG_SERVICE: 'CONFIG_SERVICE',
    REDIS_CLIENT: 'REDIS_CLIENT',
    QUEUE_CLIENT: 'QUEUE_CLIENT',
    SERVICE_BROKER: 'SERVICE_BROKER',
    SERVICE_BROKER_REQUESTOR: 'SERVICE_BROKER_REQUESTOR',
    FILES_BROKER: 'FILES_BROKER',
    NOTIFICATION_PUBLISHER: 'NOTIFICATION_PUBLISHER',
    // modules
    AUTH_SERVICE: 'AUTH_SERVICE',
    EMAIL_CONFIRM_SERVICE: 'EMAIL_CONFIRM_SERVICE',
    ADMIN_USERS_SERVICE: 'ADMIN_USERS_SERVICE',
    OAUTH_SERVICE: 'OAUTH_SERVICE',
    SYSTEM_SERVICE: 'SYSTEM_SERVICE',
    SESSION_SERVICE: 'SESSION_SERVICE',
    USER_SERVICE: 'USER_SERVICE',
    PROFILE_SERVICE: 'PROFILE_SERVICE',
    LANGUAGE_SERVICE: 'LANGUAGE_SERVICE',
    PLACE_SEARCH_ENGINE: 'PLACE_SEARCH_ENGINE',
    PLACE_SERVICE: 'PLACE_SERVICE',
    // common
    PHONE_FORMATTER: 'PHONE_FORMATTER',
}

export const OPERATIONS = {
    // auth
    ADMIN_LOGIN: 'auth.adminLogin',
    ADMIN_REGISTER: 'auth.adminRegister',
    REGISTER: 'auth.register',
    OAUTH: 'auth.oauth',
    PASS_RECOVERY: 'auth.passRecovery',
    LOGIN: 'auth.login',
    OAUTH_LOGIN: 'auth.oauthLogin',
    REFRESH_TOKEN: 'auth.refreshToken',

    // users
    EDIT_MY_PROFILE: 'users.editMyProfile',
    EDIT_PHONE_WITHOUT_CODE: 'users.editPhoneWithoutCode',
    GET_MY_PROFILE: 'users.getMyProfile',
    ADD_PROFILE_AVATARS: 'users.addAvatars',
    REMOVE_PROFILE_AVATARS: 'users.removeAvatars',
}
