export const LIMITS = {
    USER_NAME_LENGTH: [4, 30],

    MAX_SEARCH_TEXT_LENGTH: 50,
    MAX_RECORDS: 50,
    DEFAULT_RECORDS: 25,

    MIN_LANG_SEARCH_LENGTH: 2,

    MAX_MARK_TO_CONTACTS_LEN: 300,
}
