entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
  mongo:
    address: ":27017"
  redis:
    address: ":6379"
  traefik:
    address: ":8082"

traefikLog:
  logLevel: DEBUG
accessLog: {}

serversTransport:
  forwardingTimeouts:
    idleConnTimeout: 300s

providers:
  docker:
    exposedbydefault: false
    swarmmode: false
  file:
    filename: /etc/traefik/file-source.yml

api:
  dashboard: true
  insecure: true
